# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knotindex <- function(x, t) {
    .Call(`_semibmd_knotindex`, x, t)
}

deBoor <- function(x, k, t, beta, p) {
    .Call(`_semibmd_deBoor`, x, k, t, beta, p)
}

reflect <- function(xt, lb, ub) {
    .Call(`_semibmd_reflect`, xt, lb, ub)
}

bounded_newton <- function(g, gprime, bounds, xt, eps, maxitr) {
    .Call(`_semibmd_bounded_newton`, g, gprime, bounds, xt, eps, maxitr)
}

get_gamma <- function(beta) {
    .Call(`_semibmd_get_gamma`, beta)
}

Ux_cpp <- function(x, beta, knots, k, fx0, sigmaest, A) {
    .Call(`_semibmd_Ux_cpp`, x, beta, knots, k, fx0, sigmaest, A)
}

Uxd_cpp <- function(x, beta, knots, k, sigmaest) {
    .Call(`_semibmd_Uxd_cpp`, x, beta, knots, k, sigmaest)
}

get_bmd_cpp <- function(beta, knots, bounds, x0, sigmaest, A, eps, maxitr) {
    .Call(`_semibmd_get_bmd_cpp`, beta, knots, bounds, x0, sigmaest, A, eps, maxitr)
}

